# -*- coding: utf-8 -*-
"""DeployofSpeechtoText&sentimentanalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qK7XJQj1E0jQI_R3qVah8WLidB7dipMR
"""

from google.colab import drive
drive.mount("/content/drive")

!pip install -q streamlit torch torchaudio transformers librosa soundfile accelerate

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import subprocess
# import torch
# import os
# from transformers import pipeline
# 
# st.set_page_config(
#     page_title="Voice Intent & Sentiment Analyzer",
#     page_icon="🎙️",
#     layout="centered"
# )
# 
# st.title("🎙️ Voice-Based Intent & Sentiment Analysis")
# 
# DEVICE = 0 if torch.cuda.is_available() else -1
# MODEL_DIR = "/content/drive/MyDrive/voice_ai_models"
# 
# @st.cache_resource
# def load_models():
#     asr = pipeline(
#         "automatic-speech-recognition",
#         model=os.path.join(MODEL_DIR, "asr_model"),
#         device=DEVICE
#     )
#     intent = pipeline(
#         "text-classification",
#         model=os.path.join(MODEL_DIR, "intent_model"),
#         device=DEVICE
#     )
#     sentiment = pipeline(
#         "sentiment-analysis",
#         model=os.path.join(MODEL_DIR, "sentiment_model"),
#         device=DEVICE
#     )
#     return asr, intent, sentiment
# 
# asr_pipeline, intent_classifier, sentiment_analyzer = load_models()
# 
# SENTIMENT_LABEL_MAP = {
#     "LABEL_0": "Negative",
#     "LABEL_1": "Neutral",
#     "LABEL_2": "Positive"
# }
# 
# INTENT_LABEL_MAP = {
#     "NEGATIVE": "General / Neutral Intent",
#     "POSITIVE": "Affirmative / Positive Intent"
# }
# 
# def convert_to_wav_if_needed(audio_path):
#     if audio_path.lower().endswith(".wav"):
#         return audio_path
#     wav_path = audio_path.rsplit(".", 1)[0] + "_converted.wav"
#     subprocess.run(
#         ["ffmpeg", "-y", "-i", audio_path, "-ar", "16000", "-ac", "1", wav_path],
#         stdout=subprocess.DEVNULL,
#         stderr=subprocess.DEVNULL
#     )
#     return wav_path
# 
# def analyze_voice(audio_path):
#     audio_path = convert_to_wav_if_needed(audio_path)
#     transcript = asr_pipeline(audio_path)["text"]
# 
#     intent_raw = intent_classifier(transcript)[0]
#     sentiment_raw = sentiment_analyzer(transcript)[0]
# 
#     return {
#         "transcript": transcript,
#         "intent": INTENT_LABEL_MAP.get(intent_raw["label"], intent_raw["label"]),
#         "intent_confidence": round(intent_raw["score"], 3),
#         "sentiment": SENTIMENT_LABEL_MAP.get(sentiment_raw["label"], sentiment_raw["label"]),
#         "sentiment_confidence": round(sentiment_raw["score"], 3)
#     }
# 
# uploaded_file = st.file_uploader(
#     "Upload audio file (.wav, .m4a, .mp3)",
#     type=["wav", "m4a", "mp3"]
# )
# 
# if uploaded_file:
#     with open(uploaded_file.name, "wb") as f:
#         f.write(uploaded_file.getbuffer())
# 
#     st.audio(uploaded_file)
# 
#     if st.button("Analyze"):
#         with st.spinner("Analyzing audio..."):
#             result = analyze_voice(uploaded_file.name)
# 
#         st.subheader("📝 Transcription")
#         st.write(result["transcript"])
# 
#         col1, col2 = st.columns(2)
#         with col1:
#             st.metric("Intent", result["intent"], f"{result['intent_confidence']}")
#         with col2:
#             st.metric("Sentiment", result["sentiment"], f"{result['sentiment_confidence']}")
#



!streamlit run app.py

